api_name: []
items:
- _type: module
  children:
  - cntk.tests.tensor_test.test_eval_scalar
  - cntk.tests.tensor_test.test_numpy_conversion
  - cntk.tests.tensor_test.test_overload_exception
  fullName: cntk.tests.tensor_test
  module: cntk.tests.tensor_test
  name: tensor_test
  references:
  - fullName: cntk.tests.tensor_test.test_eval_scalar
    isExternal: false
    name: test_eval_scalar
    parent: ''
    uid: cntk.tests.tensor_test.test_eval_scalar
  - fullName: cntk.tests.tensor_test.test_numpy_conversion
    isExternal: false
    name: test_numpy_conversion
    parent: ''
    uid: cntk.tests.tensor_test.test_numpy_conversion
  - fullName: cntk.tests.tensor_test.test_overload_exception
    isExternal: false
    name: test_overload_exception
    parent: ''
    uid: cntk.tests.tensor_test.test_overload_exception
  source:
    id: tensor_test
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
      repo: null
    startLine: 0
  type: Namespace
  uid: cntk.tests.tensor_test
- _type: function
  fullName: cntk.tests.tensor_test.test_eval_scalar
  module: cntk.tests.tensor_test
  name: test_eval_scalar
  source:
    id: test_eval_scalar
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
      repo: null
    startLine: 19
  syntax:
    summary: ''
  type: Method
  uid: cntk.tests.tensor_test.test_eval_scalar
- _type: function
  fullName: cntk.tests.tensor_test.test_numpy_conversion
  module: cntk.tests.tensor_test
  name: test_numpy_conversion
  source:
    id: test_numpy_conversion
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
      repo: null
    startLine: 24
  syntax:
    summary: ''
  type: Method
  uid: cntk.tests.tensor_test.test_numpy_conversion
- _type: function
  fullName: cntk.tests.tensor_test.test_overload_exception
  module: cntk.tests.tensor_test
  name: test_overload_exception
  source:
    id: test_overload_exception
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/tests/tensor_test.py
      repo: null
    startLine: 13
  syntax:
    summary: ''
  type: Method
  uid: cntk.tests.tensor_test.test_overload_exception
